name: pulse_share
description: SparkTech Agency Technical Test
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.2
  analyzer: ^6.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
flutter:
  uses-material-design: true